<ItemFilter xmlns:i="http://www.w3.org/2001/XMLSchema-instance">
  <name>MR_Falconer_Leveling</name>
  <filterIcon>4</filterIcon>
  <filterIconColor>17</filterIconColor>
  <description />
  <lastModifiedInVersion>1.0.0.0</lastModifiedInVersion>
  <lootFilterVersion>2</lootFilterVersion>
  <rules>
    <Rule>
      <type>HIDE</type>
      <conditions>
        <Condition i:type="RarityCondition">
          <rarity>NORMAL MAGIC RARE</rarity>
        </Condition>
      </conditions>
      <color>0</color>
      <isEnabled>true</isEnabled>
      <levelDependent>false</levelDependent>
      <minLvl>0</minLvl>
      <maxLvl>0</maxLvl>
      <emphasized>false</emphasized>
      <nameOverride />
    </Rule>
    <Rule>
      <type>HIGHLIGHT</type>
      <conditions>
        <Condition i:type="AffixCondition">
          <affixes>
            <int>105</int>
            <int>107</int>
            <int>112</int>
            <int>113</int>
            <int>111</int>
            <int>114</int>
            <int>115</int>
            <int>116</int>
            <int>119</int>
            <int>117</int>
            <int>138</int>
            <int>124</int>
            <int>319</int>
            <int>462</int>
            <int>743</int>
            <int>491</int>
            <int>430</int>
            <int>476</int>
            <int>744</int>
            <int>527</int>
            <int>492</int>
            <int>480</int>
            <int>478</int>
          </affixes>
          <comparsion>ANY</comparsion>
          <comparsionValue>0</comparsionValue>
          <minOnTheSameItem>1</minOnTheSameItem>
          <combinedComparsion>ANY</combinedComparsion>
          <combinedComparsionValue>1</combinedComparsionValue>
          <advanced>false</advanced>
        </Condition>
      </conditions>
      <color>15</color>
      <isEnabled>true</isEnabled>
      <levelDependent>false</levelDependent>
      <minLvl>27</minLvl>
      <maxLvl>100</maxLvl>
      <emphasized>false</emphasized>
      <nameOverride>Build Idol Affixes</nameOverride>
    </Rule>
    <Rule>
      <type>HIGHLIGHT</type>
      <conditions>
        <Condition i:type="AffixCondition">
          <affixes>
            <int>462</int>
            <int>743</int>
            <int>491</int>
            <int>476</int>
            <int>744</int>
            <int>527</int>
            <int>492</int>
            <int>480</int>
            <int>478</int>
          </affixes>
          <comparsion>ANY</comparsion>
          <comparsionValue>0</comparsionValue>
          <minOnTheSameItem>2</minOnTheSameItem>
          <combinedComparsion>ANY</combinedComparsion>
          <combinedComparsionValue>1</combinedComparsionValue>
          <advanced>false</advanced>
        </Condition>
      </conditions>
      <color>15</color>
      <isEnabled>true</isEnabled>
      <levelDependent>false</levelDependent>
      <minLvl>27</minLvl>
      <maxLvl>100</maxLvl>
      <emphasized>true</emphasized>
      <nameOverride>Idols With 2 Great Affixes</nameOverride>
    </Rule>
    <Rule>
      <type>SHOW</type>
      <conditions>
        <Condition i:type="AffixCondition">
          <affixes>
            <int>28</int>
            <int>25</int>
            <int>52</int>
            <int>36</int>
            <int>80</int>
            <int>13</int>
            <int>24</int>
            <int>10</int>
            <int>7</int>
            <int>45</int>
            <int>672</int>
            <int>27</int>
            <int>17</int>
            <int>68</int>
            <int>75</int>
            <int>503</int>
            <int>505</int>
            <int>33</int>
            <int>432</int>
            <int>72</int>
            <int>92</int>
            <int>30</int>
            <int>463</int>
            <int>494</int>
            <int>500</int>
            <int>90</int>
            <int>22</int>
            <int>55</int>
            <int>54</int>
            <int>20</int>
            <int>433</int>
            <int>431</int>
          </affixes>
          <comparsion>MORE_OR_EQUAL</comparsion>
          <comparsionValue>2</comparsionValue>
          <minOnTheSameItem>1</minOnTheSameItem>
          <combinedComparsion>ANY</combinedComparsion>
          <combinedComparsionValue>28</combinedComparsionValue>
          <advanced>false</advanced>
        </Condition>
      </conditions>
      <color>0</color>
      <isEnabled>true</isEnabled>
      <levelDependent>true</levelDependent>
      <minLvl>0</minLvl>
      <maxLvl>19</maxLvl>
      <emphasized>false</emphasized>
      <nameOverride>Wanted Affixes Early Campaign</nameOverride>
    </Rule>
    <Rule>
      <type>HIDE</type>
      <conditions>
        <Condition i:type="SubTypeCondition">
          <type>
            <EquipmentType>ONE_HANDED_AXE</EquipmentType>
            <EquipmentType>ONE_HANDED_MACES</EquipmentType>
            <EquipmentType>ONE_HANDED_SCEPTRE</EquipmentType>
            <EquipmentType>ONE_HANDED_SWORD</EquipmentType>
            <EquipmentType>WAND</EquipmentType>
            <EquipmentType>TWO_HANDED_MACE</EquipmentType>
            <EquipmentType>TWO_HANDED_AXE</EquipmentType>
            <EquipmentType>TWO_HANDED_SPEAR</EquipmentType>
            <EquipmentType>TWO_HANDED_STAFF</EquipmentType>
            <EquipmentType>TWO_HANDED_SWORD</EquipmentType>
            <EquipmentType>SHIELD</EquipmentType>
            <EquipmentType>CATALYST</EquipmentType>
            <EquipmentType>ONE_HANDED_DAGGER</EquipmentType>
          </type>
          <subTypes />
        </Condition>
      </conditions>
      <color>0</color>
      <isEnabled>true</isEnabled>
      <levelDependent>true</levelDependent>
      <minLvl>0</minLvl>
      <maxLvl>19</maxLvl>
      <emphasized>false</emphasized>
      <nameOverride>Useless Bases Early Campaign</nameOverride>
    </Rule>
    <Rule>
      <type>HIGHLIGHT</type>
      <conditions>
        <Condition i:type="AffixCondition">
          <affixes>
            <int>619</int>
            <int>729</int>
            <int>614</int>
            <int>28</int>
          </affixes>
          <comparsion>ANY</comparsion>
          <comparsionValue>0</comparsionValue>
          <minOnTheSameItem>1</minOnTheSameItem>
          <combinedComparsion>ANY</combinedComparsion>
          <combinedComparsionValue>1</combinedComparsionValue>
          <advanced>false</advanced>
        </Condition>
      </conditions>
      <color>7</color>
      <isEnabled>true</isEnabled>
      <levelDependent>true</levelDependent>
      <minLvl>0</minLvl>
      <maxLvl>19</maxLvl>
      <emphasized>true</emphasized>
      <nameOverride> High Value Affixes Early Campaign</nameOverride>
    </Rule>
    <Rule>
      <type>SHOW</type>
      <conditions>
        <Condition i:type="AffixCondition">
          <affixes>
            <int>28</int>
            <int>25</int>
            <int>52</int>
            <int>36</int>
            <int>80</int>
            <int>13</int>
            <int>24</int>
            <int>10</int>
            <int>7</int>
            <int>45</int>
            <int>19</int>
            <int>86</int>
            <int>429</int>
            <int>27</int>
            <int>17</int>
            <int>56</int>
            <int>75</int>
            <int>57</int>
            <int>503</int>
            <int>505</int>
            <int>33</int>
            <int>432</int>
            <int>6</int>
            <int>92</int>
            <int>30</int>
            <int>463</int>
            <int>729</int>
            <int>728</int>
            <int>739</int>
            <int>727</int>
            <int>642</int>
            <int>619</int>
            <int>528</int>
            <int>477</int>
            <int>479</int>
            <int>481</int>
            <int>442</int>
            <int>26</int>
            <int>64</int>
            <int>643</int>
            <int>330</int>
            <int>34</int>
            <int>5</int>
            <int>431</int>
            <int>433</int>
            <int>672</int>
          </affixes>
          <comparsion>MORE_OR_EQUAL</comparsion>
          <comparsionValue>2</comparsionValue>
          <minOnTheSameItem>1</minOnTheSameItem>
          <combinedComparsion>ANY</combinedComparsion>
          <combinedComparsionValue>28</combinedComparsionValue>
          <advanced>false</advanced>
        </Condition>
      </conditions>
      <color>0</color>
      <isEnabled>true</isEnabled>
      <levelDependent>true</levelDependent>
      <minLvl>20</minLvl>
      <maxLvl>54</maxLvl>
      <emphasized>false</emphasized>
      <nameOverride>Wanted Affixes Mid Campaign</nameOverride>
    </Rule>
    <Rule>
      <type>HIDE</type>
      <conditions>
        <Condition i:type="SubTypeCondition">
          <type>
            <EquipmentType>ONE_HANDED_SWORD</EquipmentType>
            <EquipmentType>ONE_HANDED_SCEPTRE</EquipmentType>
            <EquipmentType>ONE_HANDED_AXE</EquipmentType>
            <EquipmentType>TWO_HANDED_AXE</EquipmentType>
            <EquipmentType>TWO_HANDED_MACE</EquipmentType>
            <EquipmentType>TWO_HANDED_SPEAR</EquipmentType>
            <EquipmentType>TWO_HANDED_STAFF</EquipmentType>
            <EquipmentType>TWO_HANDED_SWORD</EquipmentType>
            <EquipmentType>CATALYST</EquipmentType>
            <EquipmentType>SHIELD</EquipmentType>
            <EquipmentType>ONE_HANDED_MACES</EquipmentType>
            <EquipmentType>WAND</EquipmentType>
            <EquipmentType>ONE_HANDED_DAGGER</EquipmentType>
          </type>
          <subTypes />
        </Condition>
      </conditions>
      <color>0</color>
      <isEnabled>true</isEnabled>
      <levelDependent>true</levelDependent>
      <minLvl>20</minLvl>
      <maxLvl>54</maxLvl>
      <emphasized>false</emphasized>
      <nameOverride>Unused Weapons Mid Campaign</nameOverride>
    </Rule>
    <Rule>
      <type>HIGHLIGHT</type>
      <conditions>
        <Condition i:type="AffixCondition">
          <affixes>
            <int>619</int>
            <int>52</int>
            <int>642</int>
            <int>36</int>
            <int>614</int>
            <int>729</int>
            <int>728</int>
            <int>727</int>
          </affixes>
          <comparsion>ANY</comparsion>
          <comparsionValue>0</comparsionValue>
          <minOnTheSameItem>1</minOnTheSameItem>
          <combinedComparsion>ANY</combinedComparsion>
          <combinedComparsionValue>1</combinedComparsionValue>
          <advanced>false</advanced>
        </Condition>
      </conditions>
      <color>7</color>
      <isEnabled>true</isEnabled>
      <levelDependent>true</levelDependent>
      <minLvl>0</minLvl>
      <maxLvl>54</maxLvl>
      <emphasized>true</emphasized>
      <nameOverride> High Value Affixes Mid Campaign</nameOverride>
    </Rule>
    <Rule>
      <type>HIGHLIGHT</type>
      <conditions>
        <Condition i:type="AffixCondition">
          <affixes>
            <int>437</int>
            <int>439</int>
            <int>440</int>
            <int>442</int>
            <int>443</int>
            <int>446</int>
            <int>448</int>
            <int>449</int>
            <int>451</int>
            <int>453</int>
            <int>454</int>
            <int>457</int>
            <int>459</int>
            <int>461</int>
            <int>463</int>
            <int>468</int>
            <int>469</int>
            <int>471</int>
            <int>473</int>
            <int>475</int>
            <int>477</int>
            <int>479</int>
            <int>481</int>
            <int>483</int>
            <int>485</int>
            <int>487</int>
            <int>489</int>
            <int>494</int>
            <int>496</int>
            <int>498</int>
            <int>500</int>
            <int>509</int>
            <int>511</int>
            <int>513</int>
            <int>515</int>
            <int>517</int>
            <int>519</int>
            <int>521</int>
            <int>524</int>
            <int>526</int>
            <int>528</int>
            <int>530</int>
            <int>532</int>
            <int>534</int>
            <int>536</int>
            <int>537</int>
            <int>608</int>
            <int>609</int>
            <int>610</int>
            <int>611</int>
            <int>612</int>
            <int>613</int>
            <int>614</int>
            <int>615</int>
            <int>616</int>
            <int>617</int>
            <int>618</int>
            <int>619</int>
            <int>620</int>
            <int>638</int>
            <int>640</int>
            <int>641</int>
            <int>642</int>
            <int>662</int>
            <int>727</int>
            <int>728</int>
            <int>729</int>
            <int>730</int>
            <int>731</int>
            <int>739</int>
          </affixes>
          <comparsion>ANY</comparsion>
          <comparsionValue>0</comparsionValue>
          <minOnTheSameItem>1</minOnTheSameItem>
          <combinedComparsion>ANY</combinedComparsion>
          <combinedComparsionValue>1</combinedComparsionValue>
          <advanced>false</advanced>
        </Condition>
      </conditions>
      <color>1</color>
      <isEnabled>true</isEnabled>
      <levelDependent>true</levelDependent>
      <minLvl>54</minLvl>
      <maxLvl>100</maxLvl>
      <emphasized>false</emphasized>
      <nameOverride>Class Affixes For Storage/Removal/Shatter</nameOverride>
    </Rule>
    <Rule>
      <type>SHOW</type>
      <conditions>
        <Condition i:type="AffixCondition">
          <affixes>
            <int>28</int>
            <int>25</int>
            <int>52</int>
            <int>36</int>
            <int>80</int>
            <int>13</int>
            <int>24</int>
            <int>10</int>
            <int>7</int>
            <int>45</int>
            <int>19</int>
            <int>86</int>
            <int>429</int>
            <int>27</int>
            <int>17</int>
            <int>56</int>
            <int>75</int>
            <int>57</int>
            <int>503</int>
            <int>505</int>
            <int>33</int>
            <int>432</int>
            <int>6</int>
            <int>92</int>
            <int>30</int>
            <int>463</int>
            <int>729</int>
            <int>728</int>
            <int>739</int>
            <int>727</int>
            <int>642</int>
            <int>619</int>
            <int>528</int>
            <int>477</int>
            <int>479</int>
            <int>481</int>
            <int>442</int>
            <int>26</int>
            <int>64</int>
            <int>643</int>
            <int>330</int>
            <int>34</int>
            <int>5</int>
            <int>431</int>
            <int>433</int>
            <int>672</int>
          </affixes>
          <comparsion>MORE_OR_EQUAL</comparsion>
          <comparsionValue>2</comparsionValue>
          <minOnTheSameItem>2</minOnTheSameItem>
          <combinedComparsion>ANY</combinedComparsion>
          <combinedComparsionValue>28</combinedComparsionValue>
          <advanced>false</advanced>
        </Condition>
      </conditions>
      <color>0</color>
      <isEnabled>true</isEnabled>
      <levelDependent>true</levelDependent>
      <minLvl>55</minLvl>
      <maxLvl>101</maxLvl>
      <emphasized>false</emphasized>
      <nameOverride>Wanted Items Early endgame</nameOverride>
    </Rule>
    <Rule>
      <type>HIDE</type>
      <conditions>
        <Condition i:type="SubTypeCondition">
          <type>
            <EquipmentType>TWO_HANDED_AXE</EquipmentType>
            <EquipmentType>TWO_HANDED_MACE</EquipmentType>
            <EquipmentType>TWO_HANDED_SPEAR</EquipmentType>
            <EquipmentType>TWO_HANDED_STAFF</EquipmentType>
            <EquipmentType>TWO_HANDED_SWORD</EquipmentType>
            <EquipmentType>CATALYST</EquipmentType>
            <EquipmentType>ONE_HANDED_AXE</EquipmentType>
            <EquipmentType>ONE_HANDED_MACES</EquipmentType>
            <EquipmentType>ONE_HANDED_SCEPTRE</EquipmentType>
            <EquipmentType>ONE_HANDED_SWORD</EquipmentType>
            <EquipmentType>WAND</EquipmentType>
            <EquipmentType>ONE_HANDED_DAGGER</EquipmentType>
            <EquipmentType>SHIELD</EquipmentType>
          </type>
          <subTypes />
        </Condition>
      </conditions>
      <color>0</color>
      <isEnabled>true</isEnabled>
      <levelDependent>true</levelDependent>
      <minLvl>55</minLvl>
      <maxLvl>101</maxLvl>
      <emphasized>false</emphasized>
      <nameOverride>Unwanted Weapon and Offhand Bases</nameOverride>
    </Rule>
    <Rule>
      <type>HIGHLIGHT</type>
      <conditions>
        <Condition i:type="AffixCondition">
          <affixes>
            <int>619</int>
            <int>52</int>
            <int>642</int>
            <int>36</int>
            <int>729</int>
            <int>728</int>
            <int>727</int>
          </affixes>
          <comparsion>ANY</comparsion>
          <comparsionValue>0</comparsionValue>
          <minOnTheSameItem>1</minOnTheSameItem>
          <combinedComparsion>ANY</combinedComparsion>
          <combinedComparsionValue>1</combinedComparsionValue>
          <advanced>false</advanced>
        </Condition>
      </conditions>
      <color>7</color>
      <isEnabled>true</isEnabled>
      <levelDependent>true</levelDependent>
      <minLvl>55</minLvl>
      <maxLvl>101</maxLvl>
      <emphasized>true</emphasized>
      <nameOverride>High Value Affixes Early endgame</nameOverride>
    </Rule>
    <Rule>
      <type>HIDE</type>
      <conditions>
        <Condition i:type="ClassCondition">
          <req>Primalist Mage Sentinel Acolyte</req>
        </Condition>
      </conditions>
      <color>0</color>
      <isEnabled>true</isEnabled>
      <levelDependent>true</levelDependent>
      <minLvl>3</minLvl>
      <maxLvl>100</maxLvl>
      <emphasized>false</emphasized>
      <nameOverride>Non-Class Items</nameOverride>
    </Rule>
    <Rule>
      <type>SHOW</type>
      <conditions>
        <Condition i:type="RarityCondition">
          <rarity>UNIQUE SET</rarity>
        </Condition>
      </conditions>
      <color>0</color>
      <isEnabled>true</isEnabled>
      <levelDependent>false</levelDependent>
      <minLvl>0</minLvl>
      <maxLvl>0</maxLvl>
      <emphasized>true</emphasized>
      <nameOverride />
    </Rule>
    <Rule>
      <type>SHOW</type>
      <conditions>
        <Condition i:type="RarityCondition">
          <rarity>EXALTED</rarity>
        </Condition>
      </conditions>
      <color>0</color>
      <isEnabled>true</isEnabled>
      <levelDependent>false</levelDependent>
      <minLvl>0</minLvl>
      <maxLvl>0</maxLvl>
      <emphasized>false</emphasized>
      <nameOverride />
    </Rule>
    <Rule>
      <type>SHOW</type>
      <conditions>
        <Condition i:type="RarityCondition">
          <rarity>NORMAL MAGIC RARE UNIQUE SET EXALTED</rarity>
        </Condition>
      </conditions>
      <color>0</color>
      <isEnabled>true</isEnabled>
      <levelDependent>true</levelDependent>
      <minLvl>0</minLvl>
      <maxLvl>2</maxLvl>
      <emphasized>false</emphasized>
      <nameOverride>every first area items</nameOverride>
    </Rule>
    <Rule>
      <type>SHOW</type>
      <conditions>
        <Condition i:type="AffixCondition">
          <affixes>
            <int>676</int>
            <int>677</int>
            <int>678</int>
            <int>679</int>
            <int>673</int>
            <int>674</int>
            <int>675</int>
            <int>710</int>
            <int>711</int>
            <int>712</int>
            <int>713</int>
            <int>714</int>
            <int>701</int>
            <int>700</int>
            <int>702</int>
            <int>703</int>
            <int>704</int>
            <int>705</int>
            <int>706</int>
            <int>698</int>
            <int>699</int>
            <int>707</int>
            <int>708</int>
          </affixes>
          <comparsion>ANY</comparsion>
          <comparsionValue>0</comparsionValue>
          <minOnTheSameItem>1</minOnTheSameItem>
          <combinedComparsion>ANY</combinedComparsion>
          <combinedComparsionValue>1</combinedComparsionValue>
          <advanced>false</advanced>
        </Condition>
      </conditions>
      <color>0</color>
      <isEnabled>true</isEnabled>
      <levelDependent>false</levelDependent>
      <minLvl>0</minLvl>
      <maxLvl>0</maxLvl>
      <emphasized>false</emphasized>
      <nameOverride>Experimental affixes and personal items</nameOverride>
    </Rule>
  </rules>
</ItemFilter>
